### PR TITLE
feat: Include all ETS2 cities from v1.45.3.0

### LINKED ISSUE #3: Please update cities
I would like to get the cities updated to the latest version as of now, driving on spain, portugal or other newer countries defaults to the nearest position, In my case Toulouse (FR)

### PR DESCRIPTION
**Pull request by PabloGirol**
Closes #3
This adds all the newer cities from all DLCs.
Some country codes might be wrong since I used a python library to parse them and I dont really have time to look at 282 of them.

### CODE REVIEW

**Comment by PabloGirol** [comment]
Seems to be working fine to me, but I dont understand why you told me x and z were switched, seems to work fine on my side.

imagen


Also I dont know If Ill keep making PRs for later updates, It is a lengthy process and really buggy using that coordinate retrieve software, but I would like to

**Comment by Tarasa24** [comment]
Awesome, thank you for your work. Regarding the coordinates switch, I might be just misremembering things hah. And as you said, retrieving the coordinates is just painful and I am sure there have to be another way of obtaining them directly from gamefiles (.scs files are basically zip files anyways), so that's also worth exploring.

To be honest this whole project deserves a rework and I will try to find time for it eventually, but update like this definitely helps and is applicable to any protentional updates.

Merging now.

**Comment by PabloGirol** [comment]
I found a better way of getting the coordinates, I tested the software of the repository Unicor-p/ts-map on a pre-release (the latest stable release crashes reading job data) and it seems to read directly of the scs files.
This software claims to work both on ATS and ETS, so getting a copy with all DLCs to export city data should speed up city updates

Also it can retrieve coordinates, countryId, country, city names, and even Localized names for every language, all as a JSON file, this could be usable for translations too!
This both City names and Countries.

Its also very configurable on exports, like including Localized Names or not, also parsing this should be easy enough, as it takes less than 10 seconds to export them

This should be an example of exporting with all data
imagen

**Comment by Tarasa24** [comment]
Oh wow, great find. This bumped rework of this quite high in my todo list, when I don't have to make the coordinates retrieval from scratch. 
It gives me couple of ideas of setting up actions to compile fresh dlls, whenever there is new dlc/version and someone would make a PR with the new coords.

**Comment by PabloGirol** [comment]
Cool, just a little issue here is that we dont have the Z coordinates, either we could use a default value like from 58-100 or stop using it in the near future or even find a way to implement it manually with a fork of it.
Either way, Im happy that this proyect ill get reworked and supported at least for now

I will be looking for some way to get the Z coordinates later today and make a pr with updated coordinates for ATS

**Comment by Tarasa24** [comment]
Technically we don't even need Y coord since internally its using 2d tree. Anyways I'll wait for your PR and then make a historic v1 branch and basically nuke master and start again (better this time hopefully).

**Pull request merged**
